version: '3.6'
services:
  websockets-app-node:
    build: ./websocket
    image: ag/websockets-app6
    ports:
      - "3000:3000"
    container_name: websocket-app
  sse-app-node:
    build: ./SSE
    image: sahmed/node-sse-app21
    ports:
    - "3010:3010"
    container_name: sse-app
